In [2]:
import pandas as pd

txn = pd.read_csv(r"D:\PROJECTS\customer-churn-prediction\transactions_v2.csv\data\churn_comp_refresh\transactions_v2.csv",
                  parse_dates=['transaction_date','membership_expire_date'])
print(txn.shape)
txn.head()

(1431009, 9)

,msno,payment_method_id,payment_plan_days,plan_list_price,actual_amount_paid,is_auto_renew,transaction_date,membership_expire_date,is_cancel
0,++6eU4LsQ3UQ20ILS7d99XK8WbiVgbyYL4FUgzZR134=,32,90,298,298,0,2017-01-31,2017-05-04,0
1,++lvGPJOinuin/8esghpnqdljm6NXS8m8Zwchc7gOeA=,41,30,149,149,1,2015-08-09,2019-04-12,0
2,+/GXNtXWQVfKrEDqYAzcSw2xSPYMKWNj22m+5XkVQZc=,36,30,180,180,1,2017-03-03,2017-04-22,0
3,+/w1UrZwyka4C9oNH3+Q8fUf3fD8R3EwWrx57ODIsqk=,36,30,180,180,1,2017-03-29,2017-03-31,1
4,+00PGzKTYqtnb65mPKPyeHXcZEwqiEzktpQksaaSC3c=,41,30,99,99,1,2017-03-23,2017-04-23,0

In [3]:
txn_sorted = txn.sort_values('transaction_date')

txn_agg = txn_sorted.groupby('msno').agg(
    last_price        = ('plan_list_price', 'last'),
    last_paid         = ('actual_amount_paid', 'last'),
    last_auto_renew   = ('is_auto_renew', 'last'),
    last_cancel       = ('is_cancel', 'last'),
    total_cancels     = ('is_cancel', 'sum'),
    num_transactions  = ('transaction_date', 'count'),
    last_expire       = ('membership_expire_date', 'last'),
).reset_index()

print(txn_agg.shape)
txn_agg.head()

(1197050, 8)

,msno,last_price,last_paid,last_auto_renew,last_cancel,total_cancels,num_transactions,last_expire
0,+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=,1599,1599,0,0,0,1,2018-02-06
1,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,99,99,1,0,0,1,2017-04-15
2,+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,149,149,1,0,0,2,2017-05-19
3,+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,149,149,1,0,0,1,2017-04-26
4,++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=,149,149,1,0,0,1,2017-04-15

In [4]:
txn_agg.to_csv('txn_agg.csv', index=False)
print("Saved txn_agg.csv")

Saved txn_agg.csv